name: timenart
favicon: null
layout_spectrum: 0.7683139161672443
typography_spectrum: 0.44236049917526543
title: 'Time and Art offer different Grandfather Clocks, Wall Clocks, Table Clocks & Cuckoo Clocks of best quality.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5
  lightness: 0.8125
  saturation: 0.9375
  rhythmicContrast: 0.1292049097828567
purpose: []
