name: timenart
favicon: null
layout_spectrum: 0.99133
typography_spectrum: 0.52835
title: 'Everything clocks '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#323b42'
    - '#7b571b'
    - '#e9e0b9'
    - '#95916b'
    - '#d2aa4b'
  brandStrength: 0.25
  lightness: 0.14527
  saturation: 0.125
  rhythmicContrast: 0.75
purpose: []
