name: timenart
favicon: null
layout_spectrum: 0.99133
typography_spectrum: 0.52835
title: 'Everything clocks '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfdfd'
    - '#f1f1f1'
    - '#e1e1e1'
    - '#d4d4d4'
    - '#cbcbcb'
  brandStrength: 0.9375
  lightness: 0.9375
  saturation: 0.1875
  rhythmicContrast: 0
purpose: []
