analytics: {}
color:
  brandColors:
    - '#000000'
    - '#2b2c2e'
    - '#64655f'
    - '#fefefe'
    - '#9e9c90'
  brandStrength: 0.716216
  lightness: 0.14527
  rhythmicContrast: 0.516891
  saturation: 0.689189
cta: {}
layout_spectrum: 0.018018
name: timenart
opengraph: {}
purpose: []
typography_spectrum: 0.44236049917526543
