name: timenart
favicon: null
layout_spectrum: 0.99133
typography_spectrum: 0.52835
title: 'Everything clocks '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfdff'
    - '#efdcce'
    - '#e7c5a0'
    - '#cf9ca5'
    - '#bc6748'
  brandStrength: 0.9375
  lightness: 0.9375
  saturation: 0.1875
  rhythmicContrast: 0
purpose: []
