name: timenart
favicon: null
layout_spectrum: 0.018018
typography_spectrum: 0.23427
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#2b2c2e'
    - '#64655f'
    - '#fefefe'
    - '#9e9c90'
  brandStrength: 0.716216
  lightness: 0.14527
  saturation: 0.689189
  rhythmicContrast: 0.516891
purpose: []
